name: Update README2

on:
  schedule:
    
cron: "* /12 * *"
workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      
uses: actions/checkout@v4.2.2
uses: SpikyWiky/github-activity-readme@master
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
